#!/usr/bin/env ruby
require "optparse"
require "disget"
require "discogs-wrapper"
require "tty"
require "tty-spinner"

discog = Discogs::Wrapper.new("disget")

disget = Disget::Robot.new

options = {}
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: disget [options] RELEASE-ID"

  opts.on("-v", "--version", "print discog-get version") do |v|
    options[:version] = v
  end
end

option_parser.parse!

if options[:version]
  puts "Version: #{Disget::VERSION}"
  puts " "
end

if ARGV.size < 1
  puts option_parser.help
else
  release_id = ARGV[0]

  begin
    release = discog.get_release(release_id)
    artist = release[:artists].first[:name]
    release_name = release[:title]

    puts "release: #{artist} - #{release_name}"

    release[:tracklist].each do |track|
      getting = TTY::Spinner.new("[:spinner] getting: #{track[:title]}")
      getting.spin
      youtube_url = disget.search("#{artist} - #{track[:title]}")
      system "youtube-dl --quiet --extract-audio --embed-thumbnail --audio-format mp3 --audio-quality 0 --metadata-from-title '%(artist)s - %(title)s' -o '%(title)s.%(ext)s' #{youtube_url}"
      getting.stop('(successful)')
    end

    puts "done:"
  rescue Exception => e
    puts "#{e}!"
  end
end
